Set MSVC in Opam. Pin DKML patches

diff --git a/.github/workflows/setup-dkml.yml b/.github/workflows/setup-dkml.yml
--- a/.github/workflows/setup-dkml.yml
+++ b/.github/workflows/setup-dkml.yml
@@ -2,6 +2,8 @@ name: setup-dkml
 
 env:
   DEFAULT_DISKUV_OPAM_REPOSITORY_TAG: "19372192396b46dc51900022a19373fc1f2188e7" # "v0.4.0-prerel19_r2" when released
+  PIN_OCAMLFIND: "1.9.1"
+  PIN_OCAMLBUILD: "0.14.0"
 
 on:
   workflow_call:
@@ -42,6 +44,37 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
+        # bootstrap-opam-version
+        #   We need an old working Opam; see BOOTSTRAPPING.md of dkml-installer repository.
+        #   We use https://github.com/diskuv/dkml-installer-ocaml/releases
+        #   to get an old one; you specify its version number here.
+        #   Special value of 'os' means use the OS's package manager
+        #   (yum/apt/brew).
+        # opam-root
+        #   We need a stable location for OPAMROOT even if the version of Opam
+        #   changes (there are two versions: bootstrap and the compiled one).
+        # vsstudio-hostarch
+        #   Only needed if `os: windows-*`. The ARCH in
+        #   `vsdevcmd.bat -host_arch=ARCH`. Example: x64.
+        #   If you have a 64-bit Intel machine you should not use x86 because
+        #   _WIN64 will be defined (see https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170)
+        #   which is based on the host machine architecture (unless you explicitly
+        #   cross-compile with different ARCHs; that is, -host_arch=x64 -arch=x75).
+        #   Confer: https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170#use-the-developer-tools-in-an-existing-command-window
+        #   If you see ppx problems with missing _BitScanForward64 then
+        #   https://github.com/janestreet/base/blob/8993e35ba2e83e5020b2deb548253ef1e4a699d4/src/int_math_stubs.c#L25-L32
+        #   has been compiled with the wrong host architecture.
+        # vsstudio-arch
+        #   Only needed if `os: windows-*`. The ARCH in
+        #   `vsdevcmd.bat -arch=ARCH`. Example: x86.
+        #   Confer: https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170#use-the-developer-tools-in-an-existing-command-window
+        # dkml-options:
+        #   Space separated list of `dkml-option-*` packages.
+        #
+        #   Use 32-bit installers when possible for maximum portability of
+        #   OCaml bytecode. macos is only the major platform without 32-bit.
+        #   You don't need to include `dkml-option-32bit` because it is auto
+        #   chosen when the target ABI ends with x86.
         include:
           - os: windows-2019 # 2019 has Visual Studio 2019
             dist_name: windows
@@ -50,15 +83,12 @@ jobs:
             # The 32-bit Opam binary has some problems with
             # `Unix.create_process` giving:
             #   "create_process" failed on sleep: Bad file descriptor
-            # So use 64-bit Opam binary
-            opam-abi: windows_x86 #_64
+            # So use 64-bit Opam binary?
+            opam-abi: windows_x86_64
             dkml-target-abi: windows_x86
             opam-root: D:/.opam
-            # vsstudio-dir: C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise
-            # vsstudio-vcvarsver: "14.25"
-            # vsstudio-winsdkver: "10.0.18362.0"
-            # vsstudio-hostarch: x86
-            # vsstudio-arch: x86
+            vsstudio-hostarch: x86
+            vsstudio-arch: x86
     runs-on: ${{ matrix.os }}
     name: ${{ matrix.dist_name }}
 
@@ -69,7 +99,7 @@ jobs:
 
       # Increase if you get `make inconsistent assumptions over interface Stdlib__format` errors
       # or if you otherwise need a fresh Opam root
-      CACHE_PREFIX: ${{ inputs.cache-prefix }}_r1
+      CACHE_PREFIX: ${{ inputs.cache-prefix }}_r2
 
       # When non-empty, instead of building the standard components from the
       # central Opam repository, use the github/gitlab development repositories
@@ -84,14 +114,11 @@ jobs:
       DKML_OPTION_32BIT:                "${{ inputs.dkml-compiler }}"
       DKML_BASE_COMPILER:               "${{ inputs.dkml-compiler }}"
 
-      # VS_DIR: ${{ matrix.vsstudio-dir }}
-      # VS_ARCH: ${{ matrix.vsstudio-arch }}
-      # VS_HOST_ARCH: ${{ matrix.vsstudio-hostarch }}
-      # VS_VCVARSVER: ${{ matrix.vsstudio-vcvarsver }}
-      # VS_WINSDKVER: ${{ matrix.vsstudio-winsdkver }}
+      VS_ARCH: ${{ matrix.vsstudio-arch }}
+      VS_HOST_ARCH: ${{ matrix.vsstudio-hostarch }}
 
       # Use an M_ prefix so don't interfere with any internal DKML use
-      # M_DKMLOPTIONS: ${{ matrix.dkml-options }}
+      M_DKMLOPTIONS: ${{ matrix.dkml-options }}
       M_DKMLTARGETABI: ${{ matrix.dkml-target-abi }}
 
     steps:
@@ -130,26 +157,6 @@ jobs:
           repository: diskuv/dkml-runtime-distribution
           path: .ci/sd4/drd
           ref: 1bf73a207e054bd60b620c863a88d7c34a0efac6
-
-      - name: Set Visual Studio environment variables (Windows)
-        if: ${{ startsWith(matrix.dist_name, 'windows') }}
-        shell: pwsh
-        run: |
-          $env:PSModulePath += "$([System.IO.Path]::PathSeparator).ci\sd4\drd\src\windows"
-          Import-Module Machine
-
-          $CompatibleVisualStudios = Get-CompatibleVisualStudios -ErrorIfNotFound
-          $CompatibleVisualStudios
-          $ChosenVisualStudio = ($CompatibleVisualStudios | Select-Object -First 1)
-          $VisualStudioProps = Get-VisualStudioProperties -VisualStudioInstallation $ChosenVisualStudio
-          $VisualStudioProps
-          echo "DKML_COMPILE_SPEC=1" >> $env:GITHUB_ENV
-          echo "DKML_COMPILE_TYPE=VS" >> $env:GITHUB_ENV
-          echo "DKML_COMPILE_VS_DIR=$($VisualStudioProps.InstallPath)" >> $env:GITHUB_ENV
-          echo "DKML_COMPILE_VS_VCVARSVER=$($VisualStudioProps.VcVarsVer)" >> $env:GITHUB_ENV
-          echo "DKML_COMPILE_VS_WINSDKVER=$($VisualStudioProps.WinSdkVer)" >> $env:GITHUB_ENV
-          echo "DKML_COMPILE_VS_MSVSPREFERENCE=$($VisualStudioProps.MsvsPreference)" >> $env:GITHUB_ENV
-          echo "DKML_COMPILE_VS_CMAKEGENERATOR=$($VisualStudioProps.CMakeGenerator)" >> $env:GITHUB_ENV
 
       - name: Uninstall MSYS2 conflicting executables (Windows)
         if: ${{ startsWith(matrix.dist_name, 'windows') }}
@@ -270,11 +277,12 @@ jobs:
             touch "$OPAMROOT/.ci.repo-init"
           fi
 
-      - name: Cache Git checkouts of Opam compiler switch
+      - name: Cache Opam compiler switch
         uses: actions/cache@v2
         with:
           path: |
             ${{ matrix.opam-root }}/dkml
+            ${{ matrix.opam-root }}/config
           key:
             ${{ runner.os }}-sd4-switch-${{ env.CACHE_PREFIX }}
 
@@ -291,9 +299,8 @@ jobs:
           #!/bin/sh
           set -eufx
           PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:$PATH"
-          ls -la $OPAMROOT
           cat $OPAMROOT/config
-          if ! opam switch list --short | grep '^dkml$'; then opam switch create dkml --repos diskuv,default --empty --yes; fi          
+          if ! opam switch list --short | grep '^dkml$'; then opam switch create dkml --repos diskuv,default --empty --yes; fi
 
       # dkml-base-compiler
 
@@ -370,10 +377,127 @@ jobs:
         shell: msys2 {0}
         run: PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:$PATH" opam pin add --yes --no-action dkml-option-32bit .ci/g/dkml-option-32bit
 
-      # Install compiler
-      - name: Install OCaml compiler
+      # ocamlfind and ocamlbuild have patches necessary for Windows in diskuv-opam-repository
+
+      - name: Pin ocamlfind ${{ env.PIN_OCAMLFIND }}, ocamlbuild ${{ env.PIN_OCAMLBUILD }}
         shell: msys2 {0}
-        run: PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:$PATH" opam upgrade dkml-base-compiler ocaml ocaml-config conf-dkml-cross-toolchain --yes
+        run: |
+          PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:$PATH"
+          opam pin add --yes --no-action -k version ocamlfind ${{ env.PIN_OCAMLFIND }}
+          opam pin add --yes --no-action -k version ocamlbuild ${{ env.PIN_OCAMLBUILD }}
+
+      # Setup C compiler
+
+      - name: Cache Visual Studio environment variables
+        uses: actions/cache@v2
+        with:
+          path: .ci/sd4/vsenv
+          key: ${{ runner.os }}-sd4-vsenv-${{ env.CACHE_PREFIX }}
+
+      - name: Get Visual Studio environment variables (Windows)
+        if: ${{ startsWith(matrix.dist_name, 'windows') }}
+        shell: pwsh
+        run: |
+          if (!(Test-Path -Path ${env:GITHUB_WORKSPACE}/.ci/sd4/vsenv)) {
+            $env:PSModulePath += "$([System.IO.Path]::PathSeparator).ci\sd4\drd\src\windows"
+            Import-Module Machine
+
+            $CompatibleVisualStudios = Get-CompatibleVisualStudios -ErrorIfNotFound
+            $CompatibleVisualStudios
+            $ChosenVisualStudio = ($CompatibleVisualStudios | Select-Object -First 1)
+            $VisualStudioProps = Get-VisualStudioProperties -VisualStudioInstallation $ChosenVisualStudio
+            $VisualStudioProps
+
+            echo "VS_DIR=$($VisualStudioProps.InstallPath)" > ${env:GITHUB_WORKSPACE}/.ci/sd4/vsenv
+            echo "VS_VCVARSVER=$($VisualStudioProps.VcVarsVer)" >> ${env:GITHUB_WORKSPACE}/.ci/sd4/vsenv
+            echo "VS_WINSDKVER=$($VisualStudioProps.WinSdkVer)" >> ${env:GITHUB_WORKSPACE}/.ci/sd4/vsenv
+            echo "VS_MSVSPREFERENCE=$($VisualStudioProps.MsvsPreference)" >> ${env:GITHUB_WORKSPACE}/.ci/sd4/vsenv
+            echo "VS_CMAKEGENERATOR=$($VisualStudioProps.CMakeGenerator)" >> ${env:GITHUB_WORKSPACE}/.ci/sd4/vsenv
+          }
+
+          Get-Content ${env:GITHUB_WORKSPACE}/.ci/sd4/vsenv >> $env:GITHUB_ENV
+
+      - name: Use Visual Studio in dkml-* Opam packages (Windows)
+        if: ${{ startsWith(matrix.dist_name, 'windows') }}
+        shell: msys2 {0}
+        run: |
+          PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:$PATH"
+
+          # Make the standard input work as an OCaml string.
+          # This currently only escapes backslashes and double quotes.
+          escape_arg_as_ocaml_string() {
+              escape_arg_as_ocaml_string_ARG=$1
+              shift
+              printf "%s" "$escape_arg_as_ocaml_string_ARG" | sed 's#\\#\\\\#g; s#"#\\"#g;'
+          }
+          E_VS_DIR=$(escape_arg_as_ocaml_string "$VS_DIR")
+          E_VS_VCVARSVER=$(escape_arg_as_ocaml_string "$VS_VCVARSVER")
+          E_VS_WINSDKVER=$(escape_arg_as_ocaml_string "$VS_WINSDKVER")
+          E_VS_MSVSPREFERENCE=$(escape_arg_as_ocaml_string "$VS_MSVSPREFERENCE")
+          E_VS_CMAKEGENERATOR=$(escape_arg_as_ocaml_string "$VS_CMAKEGENERATOR")
+
+          opam option setenv= # reset
+          opam option setenv+='DKML_COMPILE_SPEC = "1"'
+          opam option setenv+='DKML_COMPILE_TYPE = "VS"'
+          opam option setenv+="DKML_COMPILE_VS_DIR = \"$E_VS_DIR\""
+          opam option setenv+="DKML_COMPILE_VS_VCVARSVER = \"$E_VS_VCVARSVER\""
+          opam option setenv+="DKML_COMPILE_VS_WINSDKVER = \"$E_VS_WINSDKVER\""
+          opam option setenv+="DKML_COMPILE_VS_MSVSPREFERENCE = \"$E_VS_MSVSPREFERENCE\""
+          opam option setenv+="DKML_COMPILE_VS_CMAKEGENERATOR = \"$E_VS_CMAKEGENERATOR\""
+          opam option setenv+="DKML_HOST_ABI = \"$M_DKMLTARGETABI\""
+          opam option setenv # print
+
+      # Setup OCaml compiler
+
+      - name: Install OCaml compiler
+        shell: cmd
+        run: |
+          @echo OFF
+
+          REM OCaml (dkml-base-compiler) will compile fine but any other
+          REM packages (ocamlbuild, etc.) which
+          REM need a native compiler will fail without the MSVC compiler in the
+          REM PATH. There isn't a `with-dkml.exe` alternative available at
+          REM this stage of the GitHub workflow.
+          call "%VS_DIR%\Common7\Tools\VsDevCmd.bat" -no_logo -host_arch=%VS_HOST_ARCH% -arch=%VS_ARCH% -vcvars_ver=%VS_VCVARSVER% -winsdk=%VS_WINSDKVER%
+          if %ERRORLEVEL% neq 0 (
+            echo.
+            echo.The "%VS_DIR%\Common7\Tools\VsDevCmd.bat" command failed
+            echo.with exit code %ERRORLEVEL%.
+            echo.
+            exit /b %ERRORLEVEL%
+          )
+
+          REM VsDevCmd.bat turns off echo; be explicit if we want it on or off
+          @echo OFF
+
+          if "%SHOULD_POPULATE_CACHE%" == "true" (
+            if "%CAN_DOWNLOAD_ONLY%" == "true" (
+              set MOREARGS=--download-only
+              set ENVARGS=OPAMDOWNLOADJOBS=1
+            )
+          )
+          if "%M_DKMLTARGETABI:~-4%" == "_x86" (
+            set M_DKMLOPTION_32BIT=dkml-option-32bit
+          )
+
+          REM Place Opam in PATH.
+          set PATH=%GITHUB_WORKSPACE%\.ci\sd4\bs\bin;%PATH%
+
+          REM We must place MSYS2 in front of path so that MSYS2
+          REM tar.exe is used instead of Windows tar.exe. 
+          REM But setup-msys2 puts MSYS2 in a temp directory when release=false.
+          REM So we use setup-msys2's `msys2 -c` wrapper.
+          FOR /F "tokens=* usebackq" %%F IN (`msys2 -c "cygpath -aw /usr/bin"`) DO (
+            set "MSYS2BIN=%%F"
+          )
+          set PATH=%MSYS2BIN%;%PATH%
+
+          if "%__INTERNAL__WIN32_BASH_HOOK%" == "true" (
+            REM # for debugging
+            env %ENVARGS% bash
+          )
+          env %ENVARGS% opam upgrade --yes dkml-base-compiler ocaml ocaml-config conf-dkml-cross-toolchain %M_DKMLOPTIONS% %M_DKMLOPTION_32BIT% %MOREARGS%
 
       # Bundle
 
@@ -386,7 +510,7 @@ jobs:
           PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:$PATH"
 
           install -d "$GITHUB_WORKSPACE"/.ci/sd4/dist
-          tar cvCfz $OPAMROOT "$GITHUB_WORKSPACE"/.ci/sd4/dist/opamroot.tar.gz .
+          tar cvCfz $OPAMROOT "$GITHUB_WORKSPACE"/.ci/sd4/dist/opamroot.tar.gz --exclude ./dkml/.opam-switch/build --exclude ./dkml/.opam-switch/build --exclude ./dkml/.opam-switch/sources .
 
           install -v "$GITHUB_WORKSPACE"/.ci/sd4/bs/bin/opam$EXE_EXT "$GITHUB_WORKSPACE"/.ci/sd4/dist/opam${EXE_EXT}
 
