Add ManyLinux2014
Patches:
- Create Opam switch not partitioned by ManyLinux/non-ManyLinux
- Install rsync in dockcross
- Add #!/bin/sh to export-opam.sh
- Troubleshooting when installing OCaml compiler on non-Windows

diff --git a/.github/workflows/setup-dkml.yml b/.github/workflows/setup-dkml.yml
--- a/.github/workflows/setup-dkml.yml
+++ b/.github/workflows/setup-dkml.yml
@@ -158,6 +158,23 @@ jobs:
             dkml-host-abi: darwin_x86_64
             opam-root: /Users/runner/.opam
 
+          - os: ubuntu-latest
+            host_target_abis: manylinux2014-linux_x86
+            default_shell: sh
+            bootstrap-opam-version: "os"
+            dkml-host-abi: linux_x86
+            opam-root: opamroot # local directory of $GITHUB_WORKSPACE so available to dockcross
+            dockcross_image: dockcross/manylinux2014-x86
+            #   Gets rid of: WARNING: The requested image's platform (linux/386) does not match the detected host platform (linux/amd64) and no specific platform was requested
+            docker_run_extra_args: --platform linux/386
+          - os: ubuntu-latest
+            host_target_abis: manylinux2014-linux_x86_64
+            default_shell: sh
+            bootstrap-opam-version: "os"
+            dkml-host-abi: linux_x86_64
+            opam-root: opamroot # local directory of $GITHUB_WORKSPACE so available to dockcross
+            dockcross_image: dockcross/manylinux2014-x64
+
     runs-on: ${{ matrix.os }}
     name: ${{ matrix.host_target_abis }}
 
@@ -193,6 +210,8 @@ jobs:
       VS_ARCH: ${{ matrix.vsstudio-arch }}
       VS_HOST_ARCH: ${{ matrix.vsstudio-hostarch }}
 
+      SHA512_DEVNULL: "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e"
+
       # Use an M_ prefix so don't interfere with any internal DKML use
       M_DKMLOPTIONS: ${{ matrix.dkml-options }}
       M_DKMLHOSTABI: ${{ matrix.dkml-host-abi }}
@@ -218,7 +237,7 @@ jobs:
       #   patch: Needed for Opam
       #   unzip: Needed for Opam
       #   git: Needed for Opam
-      - name: Install MSYS2
+      - name: Install MSYS2 (Windows)
         if: startsWith(matrix.dkml-host-abi, 'windows')
         uses: msys2/setup-msys2@v2
         with:
@@ -252,6 +271,17 @@ jobs:
           path: .ci/sd4/drd
           ref: 1bf73a207e054bd60b620c863a88d7c34a0efac6
 
+      - name: Get dockcross and Opam prerequisites (ManyLinux)
+        if: startsWith(matrix.host_target_abis, 'manylinux')
+        run: |
+          install -d .ci/sd4
+          docker run ${{ matrix.docker_run_extra_args }} --rm "${{ matrix.dockcross_image }}" > .ci/sd4/dockcross
+          chmod +x .ci/sd4/dockcross
+
+          # rsync needs to be available, even after Docker container disappears
+          install -d .ci/sd4/bs/bin
+          .ci/sd4/dockcross sh -xc 'sudo yum install -y rsync && install -v $(command -v rsync) .ci/sd4/bs/bin'
+
       #   Bootstrap from historical release
       - name: Cache Opam bootstrap by OS
         if: matrix.bootstrap-opam-version != 'os'
@@ -267,7 +297,7 @@ jobs:
           #!/bin/sh
           set -eufx
 
-          install -d "$GITHUB_WORKSPACE"/.ci/sd4/bs/bin
+          install -d .ci/sd4/bs/bin
           wget -O "$GITHUB_WORKSPACE"/.ci/sd4/opam64.tar.xz https://github.com/fdopen/opam-repository-mingw/releases/download/0.0.0.2/opam64.tar.xz
 
           # this stalls: tar xvCfJ "$GITHUB_WORKSPACE"/.ci/sd4 "$GITHUB_WORKSPACE"/.ci/sd4/opam64.tar.xz
@@ -300,10 +330,50 @@ jobs:
             tar xfz "ocaml-$ABI-$VER.tar.gz" --strip-components=2
           fi
 
-      #   Bootstrap from package manager
+      #   Bootstrap from package manager or GitHub ocaml/opam release
       - name: Bootstrap Opam from package manager (macOS)
         if: startsWith(matrix.dkml-host-abi, 'darwin') && matrix.bootstrap-opam-version == 'os'
         run: brew install gpatch && brew install opam
+      - name: Bootstrap Opam from GitHub ocaml/opam release (Linux x86_64)
+        if: matrix.dkml-host-abi == 'linux_x86_64' && matrix.bootstrap-opam-version == 'os'
+        run: |
+          #!/bin/sh
+          set -eufx
+          install -d .ci/sd4/bs/bin
+          if [ ! -x .ci/sd4/bs/bin/opam ]; then
+            wget -O .ci/sd4/bs/bin/opam.tmp https://github.com/ocaml/opam/releases/download/2.1.2/opam-2.1.2-x86_64-linux
+            sha512_check=$(openssl sha512 2>&1 < /dev/null | cut -f 2 -d ' ')
+            if [ "x$SHA512_DEVNULL" = "x$sha512_check" ]; then
+                sha512=$(openssl sha512 ".ci/sd4/bs/bin/opam.tmp" 2> /dev/null | cut -f 2 -d ' ')
+                check="c0657ecbd4dc212587a4da70c5ff0402df95d148867be0e1eb1be8863a2851015f191437c3c99b7c2b153fcaa56cac99169c76ec94c5787750d7a59cd1fbb68b"
+                test "x$sha512" = "x$check"
+                chmod +x .ci/sd4/bs/bin/opam.tmp
+                mv .ci/sd4/bs/bin/opam.tmp .ci/sd4/bs/bin/opam
+            else
+                echo "openssl 512 option unsupported."
+                exit 61
+            fi
+          fi
+      - name: Bootstrap Opam from GitHub ocaml/opam release (Linux x86)
+        if: matrix.dkml-host-abi == 'linux_x86' && matrix.bootstrap-opam-version == 'os'
+        run: |
+          #!/bin/sh
+          set -eufx
+          install -d .ci/sd4/bs/bin
+          if [ ! -x .ci/sd4/bs/bin/opam ]; then
+            wget -O .ci/sd4/bs/bin/opam.tmp https://github.com/ocaml/opam/releases/download/2.1.2/opam-2.1.2-i686-linux
+            sha512_check=$(openssl sha512 2>&1 < /dev/null | cut -f 2 -d ' ')
+            if [ "x$SHA512_DEVNULL" = "x$sha512_check" ]; then
+                sha512=$(openssl sha512 ".ci/sd4/bs/bin/opam.tmp" 2> /dev/null | cut -f 2 -d ' ')
+                check="85a480d60e09a7d37fa0d0434ed97a3187434772ceb4e7e8faa5b06bc18423d004af3ad5849c7d35e72dca155103257fd6b1178872df8291583929eb8f884b6a"
+                test "x$sha512" = "x$check"
+                chmod +x .ci/sd4/bs/bin/opam.tmp
+                mv .ci/sd4/bs/bin/opam.tmp .ci/sd4/bs/bin/opam
+            else
+                echo "openssl 512 option unsupported."
+                exit 61
+            fi
+          fi
 
       # Build OCaml
 
@@ -316,6 +386,47 @@ jobs:
             ${{ matrix.opam-root }}/.ci.root-init
           key:
             ${{ inputs.cache-prefix }}_${{ matrix.host_target_abis }}-sd4-opamroot-${{ env.OPAM_BINARY_CACHE_KEY }}
+
+      - name: Write Opam scripts
+        run: |
+          #!/bin/sh
+          set -eufx
+
+          # empty opam repository
+          install -d .ci/sd4/eor
+          cat > .ci/sd4/eor/repo <<EOF
+          opam-version: "2.0"
+          browse: "https://opam.ocaml.org/pkg/"
+          upstream: "https://github.com/ocaml/opam-repository/tree/master/"
+          EOF
+
+          # running Opam
+          if [ -x .ci/sd4/dockcross ]; then
+
+            cat > .ci/sd4/env-opam-real <<EOF
+          #!/bin/sh
+          export PATH="/work/.ci/sd4/bs/bin:\$PATH"
+          export OPAMROOT=/work/opamroot
+          exec "\$@"
+          EOF
+            cat .ci/sd4/env-opam-real
+            chmod +x .ci/sd4/env-opam-real
+            cat > .ci/sd4/env-opam <<EOF
+          #!/bin/sh
+          exec "$GITHUB_WORKSPACE"/.ci/sd4/dockcross /work/.ci/sd4/env-opam-real "\$@"
+          EOF
+
+          else
+
+            cat > .ci/sd4/env-opam <<EOF
+          #!/bin/sh
+          export PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:\$PATH"
+          exec "\$@"
+          EOF
+
+          fi
+          cat .ci/sd4/env-opam
+          chmod +x .ci/sd4/env-opam
 
       - name: Initialize Opam root
         env:
@@ -330,15 +441,6 @@ jobs:
           #!/bin/sh
           set -eufx
 
-          # empty opam repository
-          install -d "$GITHUB_WORKSPACE"/.ci/sd4/eor
-          cat > "$GITHUB_WORKSPACE"/.ci/sd4/eor/repo <<EOF
-          opam-version: "2.0"
-          browse: "https://opam.ocaml.org/pkg/"
-          upstream: "https://github.com/ocaml/opam-repository/tree/master/"
-          EOF
-
-          PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:$PATH"
           if [ ! -e "$OPAMROOT/.ci.root-init" ]; then
             rm -rf "$OPAMROOT" # Clear any partial previous attempt
             if [ "$ISWINDOWS" = true ]; then
@@ -348,12 +450,14 @@ jobs:
                 2.0.*) echo 'download-command: wget' >> $OPAMROOT/config ;;
                 *)     opam option --yes --global download-command=wget
               esac
+            elif [ -x .ci/sd4/dockcross ]; then
+              .ci/sd4/env-opam opam init --disable-sandboxing --no-setup --kind local --bare "/work/.ci/sd4/eor"
             else
-              opam init --disable-sandboxing --no-setup --kind local --bare "$GITHUB_WORKSPACE/.ci/sd4/eor"
+              .ci/sd4/env-opam opam init --disable-sandboxing --no-setup --kind local --bare "$GITHUB_WORKSPACE/.ci/sd4/eor"
             fi
             touch "$OPAMROOT/.ci.root-init"
           fi
-          opam var --global || true
+          .ci/sd4/env-opam opam var --global || true
 
       - name: Cache Opam downloads and repositories by (host,target)
         uses: actions/cache@v2
@@ -373,15 +477,14 @@ jobs:
         run: |
           #!/bin/sh
           set -eufx
-          PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:$PATH"
           if [ -x /usr/bin/cygpath ]; then
             export TEMP=$(cygpath -am "$RUNNER_TEMP")
           fi
           if [ ! -e "$OPAMROOT/.ci.repo-init" ]; then
-            opam repository remove default --yes --all --dont-select || true
-            opam repository remove diskuv --yes --all --dont-select || true
-            opam repository add default https://opam.ocaml.org --yes --dont-select
-            opam repository add diskuv "git+https://github.com/diskuv/diskuv-opam-repository.git#${DISKUV_OPAM_REPOSITORY:-$DEFAULT_DISKUV_OPAM_REPOSITORY_TAG}" --yes --dont-select
+            .ci/sd4/env-opam opam repository remove default --yes --all --dont-select || true
+            .ci/sd4/env-opam opam repository remove diskuv --yes --all --dont-select || true
+            .ci/sd4/env-opam opam repository add default https://opam.ocaml.org --yes --dont-select
+            .ci/sd4/env-opam opam repository add diskuv "git+https://github.com/diskuv/diskuv-opam-repository.git#${DISKUV_OPAM_REPOSITORY:-$DEFAULT_DISKUV_OPAM_REPOSITORY_TAG}" --yes --dont-select
             touch "$OPAMROOT/.ci.repo-init"
           fi
 
@@ -409,9 +512,8 @@ jobs:
         run: |
           #!/bin/sh
           set -eufx
-          PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:$PATH"
           cat $OPAMROOT/config
-          if ! opam switch list --short | grep '^dkml$'; then opam switch create dkml --repos diskuv,default --empty --yes; fi
+          if ! .ci/sd4/env-opam opam switch list --short | grep '^dkml$'; then .ci/sd4/env-opam opam switch create dkml --repos diskuv,default --empty --yes; fi
 
       # The action/checkout steps used for pinning will re-use existing Git objects
       # because of caching
@@ -434,7 +536,7 @@ jobs:
 
       - name: Pin dkml-base-compiler to checkout instead of Opam repository
         if: env.DKML_BASE_COMPILER != '@repository@'
-        run: PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:$PATH" opam pin add --yes --no-action dkml-base-compiler .ci/sd4/g/dkml-base-compiler
+        run: .ci/sd4/env-opam opam pin add --yes --no-action dkml-base-compiler .ci/sd4/g/dkml-base-compiler
 
       # conf-dkml-cross-toolchain
 
@@ -448,7 +550,7 @@ jobs:
 
       - name: Pin conf-dkml-cross-toolchain to checkout instead of Opam repository
         if: env.CONF_DKML_CROSS_TOOLCHAIN != '@repository@'
-        run: PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:$PATH" opam pin add --yes --no-action conf-dkml-cross-toolchain .ci/sd4/g/conf-dkml-cross-toolchain
+        run: .ci/sd4/env-opam opam pin add --yes --no-action conf-dkml-cross-toolchain .ci/sd4/g/conf-dkml-cross-toolchain
 
       # ocaml
 
@@ -462,7 +564,7 @@ jobs:
 
       - name: Pin ocaml.4.12.1 to checkout instead of Opam repository
         if: env.INPUT_OCAML != '@repository@'
-        run: PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:$PATH" opam pin add --yes --no-action ocaml.4.12.1 .ci/sd4/g/ocaml
+        run: .ci/sd4/env-opam opam pin add --yes --no-action ocaml.4.12.1 .ci/sd4/g/ocaml
 
       # ocaml-config
 
@@ -476,7 +578,7 @@ jobs:
 
       - name: Pin ocaml-config.2 to checkout instead of Opam repository
         if: env.OCAML_CONFIG != '@repository@'
-        run: PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:$PATH" opam pin add --yes --no-action ocaml-config.2 .ci/sd4/g/ocaml-config
+        run: .ci/sd4/env-opam opam pin add --yes --no-action ocaml-config.2 .ci/sd4/g/ocaml-config
 
       # dkml-option-32bit
 
@@ -490,15 +592,14 @@ jobs:
 
       - name: Pin dkml-option-32bit to checkout instead of Opam repository
         if: env.DKML_OPTION_32BIT != '@repository@'
-        run: PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:$PATH" opam pin add --yes --no-action dkml-option-32bit .ci/sd4/g/dkml-option-32bit
+        run: .ci/sd4/env-opam opam pin add --yes --no-action dkml-option-32bit .ci/sd4/g/dkml-option-32bit
 
       # ocamlfind and ocamlbuild have patches necessary for Windows in diskuv-opam-repository
 
       - name: Pin ocamlfind ${{ env.PIN_OCAMLFIND }}, ocamlbuild ${{ env.PIN_OCAMLBUILD }}
         run: |
-          PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:$PATH"
-          opam pin add --yes --no-action -k version ocamlfind ${{ env.PIN_OCAMLFIND }}
-          opam pin add --yes --no-action -k version ocamlbuild ${{ env.PIN_OCAMLBUILD }}
+          .ci/sd4/env-opam opam pin add --yes --no-action -k version ocamlfind ${{ env.PIN_OCAMLFIND }}
+          .ci/sd4/env-opam opam pin add --yes --no-action -k version ocamlbuild ${{ env.PIN_OCAMLBUILD }}
 
       # Setup C compiler
 
@@ -572,7 +673,6 @@ jobs:
       - name: Use Visual Studio in dkml-* Opam packages (Windows)
         if: startsWith(matrix.dkml-host-abi, 'windows')
         run: |
-          PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:$PATH"
 
           # Make the standard input work as an OCaml string.
           # This currently only escapes backslashes and double quotes.
@@ -587,9 +687,13 @@ jobs:
           E_VS_MSVSPREFERENCE=$(escape_arg_as_ocaml_string "$VS_MSVSPREFERENCE")
           E_VS_CMAKEGENERATOR=$(escape_arg_as_ocaml_string "$VS_CMAKEGENERATOR")
 
-          case "$(opam --version)" in
+          case "$(.ci/sd4/env-opam opam --version)" in
             2.0.*)
-              OP=$(opam var prefix)
+              if [ -x .ci/sd4/dockcross ]; then
+                echo Opam 2.0 support in dockcross to use a portable opam var prefix not yet implemented
+                exit 67
+              fi
+              OP=$(.ci/sd4/env-opam opam var prefix)
               OPSC=$OP/.opam-switch/switch-config
               if grep setenv: $OPSC; then
                 echo "INFO: Updating switch-config. Old was:"
@@ -611,37 +715,35 @@ jobs:
               cat $OPSC # print
               ;;
             *)
-              opam option setenv= # reset
-              opam option setenv+='DKML_COMPILE_SPEC = "1"'
-              opam option setenv+='DKML_COMPILE_TYPE = "VS"'
-              opam option setenv+="DKML_COMPILE_VS_DIR = \"$E_VS_DIR\""
-              opam option setenv+="DKML_COMPILE_VS_VCVARSVER = \"$E_VS_VCVARSVER\""
-              opam option setenv+="DKML_COMPILE_VS_WINSDKVER = \"$E_VS_WINSDKVER\""
-              opam option setenv+="DKML_COMPILE_VS_MSVSPREFERENCE = \"$E_VS_MSVSPREFERENCE\""
-              opam option setenv+="DKML_COMPILE_VS_CMAKEGENERATOR = \"$E_VS_CMAKEGENERATOR\""
-              opam option setenv+="DKML_HOST_ABI = \"$M_DKMLHOSTABI\""
-              opam option setenv # print
+              .ci/sd4/env-opam opam option setenv= # reset
+              .ci/sd4/env-opam opam option setenv+='DKML_COMPILE_SPEC = "1"'
+              .ci/sd4/env-opam opam option setenv+='DKML_COMPILE_TYPE = "VS"'
+              .ci/sd4/env-opam opam option setenv+="DKML_COMPILE_VS_DIR = \"$E_VS_DIR\""
+              .ci/sd4/env-opam opam option setenv+="DKML_COMPILE_VS_VCVARSVER = \"$E_VS_VCVARSVER\""
+              .ci/sd4/env-opam opam option setenv+="DKML_COMPILE_VS_WINSDKVER = \"$E_VS_WINSDKVER\""
+              .ci/sd4/env-opam opam option setenv+="DKML_COMPILE_VS_MSVSPREFERENCE = \"$E_VS_MSVSPREFERENCE\""
+              .ci/sd4/env-opam opam option setenv+="DKML_COMPILE_VS_CMAKEGENERATOR = \"$E_VS_CMAKEGENERATOR\""
+              .ci/sd4/env-opam opam option setenv+="DKML_HOST_ABI = \"$M_DKMLHOSTABI\""
+              .ci/sd4/env-opam opam option setenv # print
               ;;
           esac
 
       - name: Capture Opam environment (Windows)
         if: startsWith(matrix.dkml-host-abi, 'windows')
         run: |
-          PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:$PATH"
 
           # convert to DOS 'SET varname=varvalue' format if not already
-          opam env > "$GITHUB_WORKSPACE"/.ci/sd4/opamenv
-          if grep -q '; export' "$GITHUB_WORKSPACE"/.ci/sd4/opamenv; then
-            opam env | grep -v '^PATH=' | sed "s#; export.*##; s#'##g; s#^#SET #; s#\\\\\\\\#\\\\#g" > "$GITHUB_WORKSPACE"/.ci/sd4/opamenv
+          .ci/sd4/env-opam opam env > .ci/sd4/opamenv
+          if grep -q '; export' .ci/sd4/opamenv; then
+            .ci/sd4/env-opam opam env | grep -v '^PATH=' | sed "s#; export.*##; s#'##g; s#^#SET #; s#\\\\\\\\#\\\\#g" > "$GITHUB_WORKSPACE"/.ci/sd4/opamenv
           fi
           cat "$GITHUB_WORKSPACE"/.ci/sd4/opamenv
 
       - name: Capture Opam environment (non-Windows)
         if: "!startsWith(matrix.dkml-host-abi, 'windows')"
         run: |
-          PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:$PATH"
-          opam env > "$GITHUB_WORKSPACE"/.ci/sd4/opamenv
-          cat "$GITHUB_WORKSPACE"/.ci/sd4/opamenv
+          .ci/sd4/env-opam opam env > .ci/sd4/opamenv
+          cat .ci/sd4/opamenv
 
       # Setup OCaml compiler
 
@@ -699,10 +801,16 @@ jobs:
       - name: Install OCaml compiler (non-Windows)
         if: "!startsWith(matrix.dkml-host-abi, 'windows')"
         run: |
-          # Place Opam, if not bootstrapped by a package manager, at start of PATH
-          export PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:$PATH"
-
-          opam upgrade --yes dkml-base-compiler ocaml ocaml-config conf-dkml-cross-toolchain $M_DKMLOPTIONS $M_DKMLOPTION_32BIT
+          if ! .ci/sd4/env-opam opam upgrade --yes dkml-base-compiler ocaml ocaml-config conf-dkml-cross-toolchain $M_DKMLOPTIONS $M_DKMLOPTION_32BIT; then
+            printf "\n\n========= [START OF TROUBLESHOOTING] ===========\n\n" >&2
+            find "$OPAMROOT"/log -mindepth 1 -maxdepth 1 -name "*.out" ! -name "log-*.out" ! -name "ocaml-variants-*.out" | while read -r dump_on_error_LOG; do
+                dump_on_error_BLOG=$(basename "$dump_on_error_LOG")
+                printf "\n\n========= [TROUBLESHOOTING] %s ===========\n\n" "$dump_on_error_BLOG" >&2
+                cat "$dump_on_error_LOG" >&2
+            done
+            printf "Scroll up to see the [TROUBLESHOOTING] logs that begin at the [START OF TROUBLESHOOTING] line\n" >&2
+            exit 109
+          fi
 
       # Bundle
 
@@ -712,7 +820,6 @@ jobs:
           set -eufx
 
           # Place Opam, if not bootstrapped by a package manager, at start of PATH
-          export PATH="$GITHUB_WORKSPACE/.ci/sd4/bs/bin:$PATH"
 
           install -d .ci/sd4/dist
 
@@ -724,7 +831,10 @@ jobs:
 
           # Distribute whichever opam.exe we have been using
           install -d .ci/sd4/d
-          install -v $(command -v opam) .ci/sd4/d/opam${EXE_EXT}
+          printf "#!/bin/sh\ninstall -v %s .ci/sd4/d/opam%s" '$(command -v opam)' "${EXE_EXT}" > .ci/sd4/export-opam.sh
+          cat .ci/sd4/export-opam.sh
+          chmod +x .ci/sd4/export-opam.sh
+          .ci/sd4/env-opam .ci/sd4/export-opam.sh          
           pwd_unix=$(pwd) # $GITHUB_WORKSPACE as a Unix path
           if [ -d .ci/sd4/bs/bin/Opam.Runtime.amd64 ]; then # include DLLs from fdopen
             cp -rp .ci/sd4/bs/bin/Opam.Runtime.amd64/ .ci/sd4/d/
