Check for switch presence after cache load

diff --git a/.github/workflows/setup-dkml.yml b/.github/workflows/setup-dkml.yml
--- a/.github/workflows/setup-dkml.yml
+++ b/.github/workflows/setup-dkml.yml
@@ -813,8 +813,25 @@ jobs:
         run: |
           #!/bin/sh
           set -eufx
-          cat $OPAMROOT/config >&2
-          if ! opamrun switch list --short | grep '^dkml$'; then opamrun switch create dkml --repos diskuv,default --empty --yes; fi
+
+          # Check if the switch name is present in the Opam root (which may come from cache)
+          NOMINALLY_PRESENT=false
+          if opamrun switch list --short | grep '^dkml$'; then NOMINALLY_PRESENT=true; fi
+
+          # Check if the switch is actually present (the switch cache is independent of the
+          # opam root cache). Inconsistencies will result in:
+          #   Error:  No config file found for switch dkml. Switch broken?
+          if [ $NOMINALLY_PRESENT = true ] && [ ! -e $OPAMROOT/dkml/.opam-switch/switch-config ]; then
+            # Remove the switch name from Opam root, and any partial switch state.
+            # Ignore inevitable warnings/failure about missing switch.
+            opamrun switch remove dkml --yes || true
+            rm -rf $OPAMROOT/dkml
+            NOMINALLY_PRESENT=false
+          fi
+
+          if [ $NOMINALLY_PRESENT = false ]; then
+            opamrun switch create dkml --repos diskuv,default --empty --yes
+          fi
 
       # The action/checkout steps used for pinning will re-use existing Git objects
       # because of caching
